# -*- coding: utf-8 -*-
"""Colab'e hoş geldiniz.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# ==========================================
# 1. VERİ SETİ OLUŞTURMA VE YÜKLEME
# ==========================================
np.random.seed(42)
boyut = 1000
df = pd.DataFrame({
    'Ates': np.random.normal(37.5, 1.0, boyut),
    'Oksuruk_Siddeti': np.random.randint(0, 10, boyut),
    'Kan_Oksijeni': np.random.normal(95, 4, boyut),
    'Yas': np.random.randint(18, 80, boyut),
    'Covid_Sonuc': np.random.choice([0, 1], boyut, p=[0.6, 0.4])
})

# Veri temizleme adımını göstermek için kasıtlı bozulan veriler:
df.loc[10:20, 'Ates'] = np.nan      # Eksik (Boş) veri
df.loc[30:35, 'Kan_Oksijeni'] = 40  # Aykırı değer (Çok düşük oksijen)

print("✅ 1. Orijinal Veri Yüklendi. Boyut:", df.shape)

# ==========================================
# 2. VERİ TEMİZLEME (ÖN İŞLEME)
# ==========================================
# Eksik verileri medyan ile dolduruyoruz
df['Ates'] = df['Ates'].fillna(df['Ates'].median())

# Aykırı değerleri filtreliyoruz (Kan oksijeni 70'ten büyük olanları tut)
df = df[df['Kan_Oksijeni'] > 70]

print("✅ 2. Eksik ve Aykırı Veriler Temizlendi. Yeni Boyut:", df.shape)

# ==========================================
# 3. VERİYİ BÖLME VE STANDARTLAŞTIRMA
# ==========================================
X = df.drop('Covid_Sonuc', axis=1) # Özellikler
y = df['Covid_Sonuc']              # Hedef (Hasta mı?)

# Eğitim ve Test olarak ayırma (%80 Eğitim,